name: climaax_multirisk_infrastructure

channels:
    - conda-forge

dependencies:
    - cartopy=0.23.0
    - cdsapi=0.7.5
    - dask=2024.7.0
    - geopandas=1.0.1
    - ipykernel=6.29.5
    - ipython=8.27.0
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.2.3
    - matplotlib=3.8.4
    - netcdf4=1.7.1
    - notebook=7.2.1
    - numpy=1.26.4
    - pandas=2.2.2
    - pip
    - python=3.11
    - rasterio=1.3.10
    - rioxarray=0.15.7
    - regionmask=0.13.0
    - scipy=1.14.0
    - xarray=2024.6.0
    - xclim=0.50.0
