name: climaax_multi_infrastructure

channels:
    - conda-forge

dependencies:
    - cartopy=0.23.0
    - cdsapi=0.7.5
    - dask=2024.7.0
    - geopandas=1.0.1
    - ipykernel=6.29.5
    - ipython=8.27.0
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.2.7
    - matplotlib=3.8.4
    - netcdf4=1.7.1
    - notebook=7.2.2
    - numpy=1.26.4
    - pandas=2.2.2
    - pip
    - python=3.12
    - rasterio=1.3.10
    - regionmask=0.13.0
    - rioxarray=0.15.7
    - scipy=1.15.2
    - tqdm=4.66.4
    - xarray=2024.6.0
    - xclim=0.50.0
    - pip:
       - gisco-geodata==0.1.2

