name: climaax_multi_infrastructure

channels:
    - conda-forge

dependencies:
    - cartopy=0.24.0
    - cdsapi=0.7.5
    - dask=2025.03.0
    - geopandas=1.0.1
    - ipykernel=6.29.5
    - ipython=9.0.2
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.3.6
    - matplotlib=3.10.1
    - netcdf4=1.7.2
    - notebook=7.3.3
    - numpy=2.1.3
    - pandas=2.2.3
    - pip
    - python=3.12.9
    - rasterio=1.4.3
    - regionmask=0.13.0
    - rioxarray=0.18.2
    - scipy=1.15.2
    - xarray=2025.3.1
    - xclim=0.55.1
